version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
      time: "18:00"
    labels:
      - dependencies
    reviewers:
      - WithoutAName25
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "18:00"
    labels:
      - dependencies
    reviewers:
      - WithoutAName25